spring.application.name=TourBuddy

server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/tour_buddy
spring.datasource.username=root
spring.datasource.password=Shadowk*4216p
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=INDUSTRIAL_SECRET_KEY_256_BIT_123456789012345
jwt.access-token-expiration=900000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=23ita31@karpagamtech.ac.in
spring.mail.password=efyp rwfy jgxy glve
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true